Home work
ediverson/Kitty pull request #1
Opened 2021-01-21 18:47 UTC by ediverson

Its done

2021-01-22 10:05 UTC, ios-review requested changes
Классное исследование возможностей swift🔥

Некоторые пункты можно рассмотреть еще глубже.

2021-01-22 10:05 UTC, ios-review commented on Mousy.playground/Contents.swift
> +}
как еще можно?

2021-01-22 10:05 UTC, ios-review commented on Mousy.playground/Contents.swift
> +}
еще способ

2021-01-22 10:05 UTC, ios-review commented on Mousy.playground/Contents.swift
> +}
"нет, но" обычно значит да)

Пример не показывает, как можно сохранить значение p.
Оно передается в инициализатор и дальше не используется.
Это значение потеряется.

https://stackoverflow.com/questions/25426780/how-to-have-stored-properties-in-swift-the-same-way-i-had-on-objective-c
https://valv0.medium.com/computed-properties-and-extensions-a-pure-swift-approach-64733768112c

Попробуйте оба способа

2021-01-22 10:05 UTC, ios-review commented on Mousy.playground/Contents.swift
> +
протоколы тоже?

2021-01-22 10:05 UTC, ios-review commented on Mousy.playground/Contents.swift
> +
примеры для каждого типа

2021-01-22 10:05 UTC, ios-review commented on Mousy.playground/Contents.swift
> +
`protocol Test: UIViewController {}`

Так можно?

2021-01-22 10:05 UTC, ios-review commented on Mousy.playground/Contents.swift
> +}
а создать псевдоним типа, который реализует одновременно несколько несвязанных между собой протоколов?

2021-01-25 11:13 UTC, ediverson commented on Mousy.playground/Contents.swift
> +
Получается, можно создавать протоколы только тех типов, что являются классами. От struct и enum нельзя

2021-01-25 11:16 UTC, ediverson commented on Mousy.playground/Contents.swift
> +}
имеется в виду typealias?

если да, то насколько я понял, туда нельзя записать сразу несколько протоколов

2021-01-25 11:17 UTC, ediverson commented on Mousy.playground/Contents.swift
> +}
> а создать псевдоним типа, который реализует одновременно несколько несвязанных между собой протоколов?

имеется в виду typealias?

если да, то насколько я понял, туда нельзя записать сразу несколько протоколов

2021-01-25 11:17 UTC, ediverson commented on Mousy.playground/Contents.swift
> +
> `protocol Test: UIViewController {}`
> 
> Так можно?

Получается, можно создавать протоколы только тех типов, что являются классами. От struct и enum нельзя

2021-01-25 11:22 UTC, ediverson commented on Mousy.playground/Contents.swift
> +
> примеры для каждого типа

extension String{
    struct Struct{
        let value = ""
    }
    protocol Game { Можно все, кроме протокола, тут сразу получаем ошибку
        func play()  
    }
    class Move {
        let value = ""
    }
    enum Anumal {
        case bird
    }
}

2021-01-25 11:25 UTC, ediverson commented on Mousy.playground/Contents.swift
> +}
> еще способ

Если объявляем конкретный тип, то можно указать вопросительный знак
var prit: String? {get}

2021-01-25 11:27 UTC, ediverson commented on Mousy.playground/Contents.swift
> +}
> как еще можно?

только если указать тип конкретного класса, иначе нельзя

2021-01-25 12:04 UTC, ediverson commented on Mousy.playground/Contents.swift
> +}
Для создания хранимого свойства, необходимо создать вложенный тип внутри extension, а из него уже добывать значения для нашей пременной/постоянной через get/set

> "нет, но" обычно значит да)
> 
> Пример не показывает, как можно сохранить значение p.
> Оно передается в инициализатор и дальше не используется.
> Это значение потеряется.
> 
> https://stackoverflow.com/questions/25426780/how-to-have-stored-properties-in-swift-the-same-way-i-had-on-objective-c
> https://valv0.medium.com/computed-properties-and-extensions-a-pure-swift-approach-64733768112c
> 
> Попробуйте оба способа

Для создания хранимого свойства, необходимо создать вложенный тип внутри extension, а из него уже добывать значения для нашей пременной/постоянной через get/set

При этом вложенный тип должен быть с префиксом private, чтобы не создаваться для каждого экземпляра расширяемого типа. А так же static, чтобы на него можно было ссылаться

2021-02-01 12:28 UTC, closed without merging