Generics
ediverson/Kitty pull request #2
Opened 2021-02-01 12:17 UTC by ediverson

2021-02-02 11:27 UTC, ios-review requested changes
Либа анимаций 🔥

По некоторым заданиям комментарии.

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> + */
👍

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> +func equate<T: Equatable>(_ a: T, _ b: T){
code-style: между отдельными выражениями нужно ставить пробелы.
Например, между закрывающейся круглой скобкой и открывающейся фигурной.
Или здесь:
`} else {`

Далее везде по коду поправить code-style

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> +    }
в задании требуется вывести большее из значений.
Сейчас во всех трех случаях выводятся оба.

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> +}
В задании требуется обменять переменные, только если a > b.
Выводить в консоль не требуется.

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> +//}
Данный код близок к решению.
```
func carry<T>(_ a: @escaping (T) -> Void, _ b: @escaping (T) -> Void) -> ((T) -> Void){
    return {
        a($0)
        b($0)
    }
}

carry( { print("\($0) a") }, { print("\($0) b") })("Hihi")
```

Прокомментируете каждое синтаксическое выражение?

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> +    }
Какова сложность (О) алгоритма сортировки в лучшем случае?
А сложность самого простого и эффективного алгоритма поиска максимального элемента?

Попробуете реализовать алгоритм с большей эффективностью?

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> +//array.removeDuplicates()
Алгоритм может быть такой:
1. Создать пустой массив.
2. Начать цикл по массиву, для которого вызывается функция removeDuplicates.
3. В теле цикла проверять есть ли элемент в массиве из пункта 1. Если его нет, то добавлять.

Реализуете?

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> +    var result = 1.0 as! T //здесь у меня ошибка, если подставлять в значение left –– не тот же тип, что и сам result. Получается если я хочу возвести в степень число типа Double, то result тоже долж
Литеральное значение числа с плавающей точкой автоматически приводится к типу Double.
Это правило, которое нельзя изменить.

Приводить тип Double к любому другому (as! T) некорректно.
swift строго-типизированный язык.

В задании не требуется реализовать возведение в степень для всех возможных чисел, которые можно умножать.
Реализуйте только для Int.

Вообще для возведения в степень тип данных должен удовлетворять большЕму количеству требований, чем просто умножение.
Еще у этого типа должно быть нейтральное значение.
Нейтральное означает то, при умножении другого значения на которое не изменяет это значение.
В общем тип должен быть группой.
https://ru.wikipedia.org/wiki/Группа_(математика)

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> +2^^3
А, уже есть)
гуд 👌

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> +}
Оператор не требует возвращаемого значения.
Достаточно только присвоить в right.

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> +}
и left и right должны быть https://developer.apple.com/documentation/swift/customstringconvertible по условию задачи.

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> +class newView: UIView{
code-style: https://swift.org/documentation/api-design-guidelines/
Имена классов/структур/перечислений/протоколов с большой буквы.
Все остальное с маленькой.

2021-02-02 11:27 UTC, ios-review commented on Mousy.playground/Contents.swift
> +        change.viewCenter(target: self, x: 5, y: 5)
🔥

2021-02-02 15:37 UTC, ediverson commented on Mousy.playground/Contents.swift
> +    }
Поправил

2021-02-02 15:38 UTC, ediverson commented on Mousy.playground/Contents.swift
> +}
Поправил

2021-02-02 15:38 UTC, ediverson commented on Mousy.playground/Contents.swift
> +//}
Закомментил

2021-02-02 15:39 UTC, ediverson commented on Mousy.playground/Contents.swift
> +}
Поправил

2021-02-02 15:39 UTC, ediverson commented on Mousy.playground/Contents.swift
> +}
Поправил

2021-02-02 15:40 UTC, ediverson commented on Mousy.playground/Contents.swift
> +class newView: UIView{
Вот скажу честно, до второго курса у меня никогда не было такой проблемы........

2021-02-02 15:43 UTC, ediverson commented on Mousy.playground/Contents.swift
> +func equate<T: Equatable>(_ a: T, _ b: T){
Поправил, но на всякий случай спрошу. При создании класса, фигурная скобка ставится тоже через пробел, верно? class NewView: UIView {

Так же в примере функции для задания 6.4 вы не указали пробел при закрытии скобок.
carry( { print("\($0) a") }, { print("\($0) b") **})**("Hihi")
Получается, мы ставим пробелы только при открытии скобок между круглыми и фигурными, а при закрытии можно обойтись без пробела. Верно?

2021-02-02 16:13 UTC, ediverson commented on Mousy.playground/Contents.swift
> +//array.removeDuplicates()
По сути именно так мой код и работает, только я почему-то был им не доволен и хотел засунуть else, который бы удалял элементы. Если честно, уже не помню, зачем я это сделал, ведь тут мы и так создаем массив result, в который передаем не повторяющиеся элементы, проверяя их через .contains

А если еще честнее, этот код я нашел в интернетах, а сам пытался сделать цикл внутри цикла. Работал он так: я создаю пустой массив, пускаю цикл по исходному, для которого вызывается функция. Заполняю каждым элементом новый массив а потом для нового массива пускаю новый цикл, в котором сравниваю элементы первого и второго массива. 

Выглядит примерно так: 

var result = [Element]()
for (index, value) in self.enumerated(){
   result.append(value)
      for (index, el) in result.enumerated(){
         if el == value{
            self.remove(at: index)
         }
      }
   }
}

2021-02-02 16:16 UTC, ediverson commented on Mousy.playground/Contents.swift
> +    }
Если честно, не понял что значит "сложность" в конкретном контексте

2021-02-03 07:34 UTC, ios-review requested changes
Предлагаю попробовать упростить реализации, а для некоторых записать более оптимальные алгоритмы.
Ок?

2021-02-03 07:34 UTC, ios-review commented on Mousy.playground/Contents.swift
> +    }
Данная реализация напечатает оба значения a и b независимо от их равенства.
Всегда будет один и тот же вывод: "6.\(count) –– a = \(a!), b = \(b!)"

Условие задания такое: в зависимости от того, равны ли они друг другу, выводит **разные** сообщения в лог;

Попробуете использовать просто print?

2021-02-03 07:34 UTC, ios-review commented on Mousy.playground/Contents.swift
> +    }
print("Equal") если равны
print("Not Equal") если неравны

2021-02-03 07:34 UTC, ios-review commented on Mousy.playground/Contents.swift
> +}
Просто print проще и надежнее.

Реализация в одну строку.
`print(a > b ? a : b)`

2021-02-03 07:34 UTC, ios-review commented on Mousy.playground/Contents.swift
> +        b = tempA
Можно ли реализовать, воспользовавшись swap?
https://developer.apple.com/documentation/swift/1540890-swap

2021-02-03 07:34 UTC, ios-review commented on Mousy.playground/Contents.swift
> +// @escaping – указываем, что параметры a и b возвращат значения после того, как возвращает значение сама функция
https://ru.stackoverflow.com/questions/877368/Работа-escaping-и-nonescaping-в-swift/877505#877505

2021-02-03 07:34 UTC, ios-review commented on Mousy.playground/Contents.swift
> +// возвращаем мы замыкание (а не функцию), в котором вызываем оба входных параметра, которые так же являютя замыканиями, иу этих параметров вызываем их же неназыванный параметр
Функции и замыкания очень близки.
Функции частный случай замыкания.
https://docs.swift.org/swift-book/LanguageGuide/Closures.html

> Global and nested functions, as introduced in Functions, are actually special cases of closures. Closures take one of three forms:

2021-02-03 07:34 UTC, ios-review commented on Mousy.playground/Contents.swift
> +array.maxEl
Вычислительная сложность алгоритма - это функция количества операций (объема работы) алгоритма от количества входных данных.

Например, простой цикл по всему массиву без дополнительных операций будет O(n), где n - количество элементов в массиве.
Линейная зависимость количества операций алгоритма от количества входных данных, то есть количества элементов массива.

Функция sorted реализована быстрой сортировкой.
Сложность этого алгоритма O(n * log n).

Существует алгоритм поиска максимального элемента со сложностью O(n).
O(n) < O(n * log n), то есть алгоритм более эффективный по производительности, так как затратит меньший объем ресурсов процессора для того же результата.

Реализуете более эффективный алгоритм?

2021-02-03 07:34 UTC, ios-review commented on Mousy.playground/Contents.swift
> +//array.removeDuplicates()
Закомментированный код верный.
Блок else избыточен. В остальном 👌

Раскоментируете и доработаете алгоритм нахождения уникальных значений?

Какой другой алгоритм можно использовать, если элементы были бы Hashable?

2021-02-03 07:38 UTC, ios-review commented on Mousy.playground/Contents.swift
> +func equate<T: Equatable>(_ a: T, _ b: T){
При создании класса ставить пробел нужно.

При записи в параметрах функции либо ставить пробел с обеих сторон, либо ни с одной.
```
carry( { print("($0) a") }, { print("($0) b") } )("Hihi")
или
carry({ print("($0) a") }, { print("($0) b") })("Hihi")
```
Здесь мне больше нравится второй вариант.
Но в целом на ваше усмотрение.

А при работе в команде по договоренностям о code style&

2021-02-03 07:41 UTC, ios-review commented on Mousy.playground/Contents.swift
> +class newView: UIView{
code style важен, потому что единый стиль очень упрощает чтение кода.
Чтение кода составляет около 80% работы программиста.

Будущие коллеги будут очень благодарны за красиво отформатированный код)

Как вы думаете, пригодится такой навык в будущем?

2021-02-03 10:08 UTC, ediverson commented on Mousy.playground/Contents.swift
> +array.maxEl
Теперь понял, спасибо. 

Самый быстрый способ из тех, что я нашел – self.max(). Но мне показалось странным использовать эту функцию, так как по сути нет особого смысла создавать расширение для такой простой функции. Можно просто задать в новую переменную имя массива и .max()
let newArray = array.max()

2021-02-03 10:11 UTC, ediverson commented on Mousy.playground/Contents.swift
> +        b = tempA
Да, в таком случае получится уместить код в одну строчку. 

Кстати гововоря про codeStyle. Корректно ли будет написать так: 
func replace<T: Comparable>(_ a: inout T, _ b: inout T) { if a > b { swap(&a, &b) } }

Или тело функции все же стоит отделить?

2021-02-03 10:14 UTC, ediverson commented on Mousy.playground/Contents.swift
> +}
😦
Да, о таком я даже не думал

2021-02-03 10:19 UTC, ediverson commented on Mousy.playground/Contents.swift
> +    }
В таком случае func equate<T: Equatable>(_ a: T, _ b: T) { print(a == b ? "Equal" : "Not Equal") }

2021-02-03 10:20 UTC, ediverson commented on Mousy.playground/Contents.swift
> +class newView: UIView{
На самом деле мне и самому нравится, когда все одинаково во всех местах. Что-то типа симметрии, только на несколько объектов сразу. Так и удобнее, и выглядит приятнее

2021-02-03 15:52 UTC, ediverson commented on Mousy.playground/Contents.swift
> +//array.removeDuplicates()
Нашел интересное решение для Hashable.
Мы создаем переменную в которую передаем Set<Element>() – Set, так как там значения не упорядочены
Дальше используем фильтр по element в нашем созданном значении и через defer добавляем значения, которые не содержатся в added. 

defer - по сути отложенное выполнение, которое реализуется непосредственно до окончания существования поля видимости, где оно указано.

2021-02-04 10:38 UTC, ios-review commented on Mousy.playground/Contents.swift
> +array.maxEl
Использование такой функции самый простой способ в продуктовом коде.
Здорово, что вы нашли этот способ👍

Еще один - это реализация алгоритма поиска максимального элемента с помощью цикла for.
```
guard var max = first else { return nil }
for element in self {
    if element > max {
        max = element
    }
}
return max
```

2021-02-04 10:41 UTC, ios-review commented on Mousy.playground/Contents.swift
> +        b = tempA
Чтение записи в одной строке сигнатуры функции и ее реализации приводит к большой когнитивной нагрузке.
Читабельно в целом, но мозгу легче воспринять раздельно сигнатуру, а отдельно тело, так как это разные конструкции по назначению и смыслу.
Поэтому их нагляднее отделить друг от друга.
```
func replace<T: Comparable>(_ a: inout T, _ b: inout T) {
    if a > b { 
        swap(&a, &b) 
    } 
}
```

В общем случае все зависит от договоренностей о code style внутри команды разработки.
Если команда состоит из одного человека, то можно делать как хочется)

2021-02-04 10:42 UTC, ios-review commented on Mousy.playground/Contents.swift
> +    }
🔥

2021-02-04 10:44 UTC, ios-review approved these changes
🔥🔥🔥

Реквест можно мержить.

2021-02-04 10:44 UTC, ios-review commented on Mousy.playground/Contents.swift
> +            if result.contains(value) == false {
`if !result.contains(value)`

Условие отрицания читается немного проще, чем равенство false.
Если резалт НЕ содержит значение == !result.contains(value)
Если не верно утверждение резалт содержит значение == result.contains(value) == false

А по вашим ощущениям, что легче для чтения?

2021-02-10 16:26 UTC, ios-review commented on Mousy.playground/Contents.swift
> +//array.removeDuplicates()
В случае Hashable элементов можно реализовать в одну строку:
`return Array(Set(self))`

Множество Set имеет неупорядоченный набор **уникальных** хэшируемых элементов.

2021-02-11 11:09 UTC, ediverson commented on Mousy.playground/Contents.swift
> +//array.removeDuplicates()
Можно и так, но в таком случае мы теряем последовательность. Если нам важен порядок, в котором расположены элементы, то Set точно не подходит

2021-02-11 11:59 UTC, ios-review requested changes
Stack 👍
Примеры type erasure 🔥

Несколько заданий можно доделать.

2021-02-11 11:59 UTC, ios-review commented on Mousy.playground/Contents.swift
>           }
`return Array(Set(self))`

2021-02-11 11:59 UTC, ios-review commented on Mousy.playground/Contents.swift
> +//2. Реализовать очередь Queue.
Структура данных очередь https://ru.wikipedia.org/wiki/Очередь_(программирование)
Необходимо было реализовать ее.

2021-02-11 11:59 UTC, ios-review commented on Mousy.playground/Contents.swift
> +    }
У stack операции чаще именуются как push/pop.
https://ru.wikipedia.org/wiki/Стек

2021-02-11 11:59 UTC, ios-review commented on Mousy.playground/Contents.swift
> +// Если честно, совсем не понял почему мой код тут при каждом запуске работает вразнобой. Сколько раз запускаю, столько вариантов получаю. Хотя по идее сначала должен сработать главный поток, а потом
DispatchQueue.async означает поставить блок кода в очередь на выполнение асинхронно, то есть фактическое выполнение кода будет при следующем цикле Run Loop.
Такое поведение независимо от типа очереди.
Если внутри этого блока кода ставится в очередь на выполнение другой код, то он будет поставлен в эту очередь отложено, так как код вызовется позже.

На 23 строке ставится блок кода, который только в следующем цикле выполнения будет реально выполнен.
Тоже для 27 строки. При этом сам блок кода не будет выполнен сразу, что означает, что не будут поставлены в очередь блоки кода с print(3) и print(5) до фактического выполнения блока на 27 строке.

Примерно такой будет процесс выполнения:
Run Loop 1:
- ставится в очередь блок на 23 строке
- ставится в очередь блок на 27 строке
Run Loop 2:
- выполняется код на 24 строке
- выполняется код на строках 28-35
при этом этот код может быть параллельно выполнен с кодом на 24 строке.
Результат не гарантирован. Может быть 1 2 4, 2 1 4, 2 4 1.
Точно последовательно будут записаны 2 и 4.
В этих строках 28-35
- ставится в очередь блок кода на 29 строке
- ставится в очередь блок кода на 33 строке
Run Loop 3:
- выполняется код на 30 строке
- выполняется код на 34 строке

2021-02-11 11:59 UTC, ios-review commented on Mousy.playground/Contents.swift
> +// В статье написано про пример из Swift Standard Library - AnySequence, но разве под это не подходят вообще все протоколы с префиксом Any? (AnyHashable, AnyIterator, AnyCollection) Они все нужны при
type-erasure используют для возможности использовать дженерик протокол как тип данных

2021-02-11 11:59 UTC, ios-review commented on Mousy.playground/Contents.swift
> +let creatures = [AnyCreature(Eagle())] // Если захотим добавить сда AnyCreature(Plane()), то получим ошибку, так как класс Eagle и Plane относятся к разным типам. Eagle - Animal, а Plane - Item
Пример 🔥

2021-02-11 11:59 UTC, ios-review commented on Mousy.playground/Contents.swift
> +// на самом деле нашел тут интересную страничку https://riptutorial.com/swift/example/23548/precedence-of-standard-swift-operators. По сути тут расписаны приоритет и ассоциативность для каждого опера
Не уверен, что понял про пробел.
Поделитесь ссылкой на источник, где утверждается, что пробел - оператор?

2021-02-11 11:59 UTC, ios-review commented on Mousy.playground/Contents.swift
> +//10. Реализовать любой infix, prefix, postfix операторы.
Реализация самих операторов не представлена.
Необходимо реализовать свои собственные операторы для любых типов на ваше усмотрение.

2021-02-13 15:15 UTC, ediverson commented on Mousy.playground/Contents.swift
> +// на самом деле нашел тут интересную страничку https://riptutorial.com/swift/example/23548/precedence-of-standard-swift-operators. По сути тут расписаны приоритет и ассоциативность для каждого опера
https://riptutorial.com/swift/example/23548/precedence-of-standard-swift-operators

в таблице 3 значение снизу

2021-02-13 15:39 UTC, ediverson commented on Mousy.playground/Contents.swift
> +// Если честно, совсем не понял почему мой код тут при каждом запуске работает вразнобой. Сколько раз запускаю, столько вариантов получаю. Хотя по идее сначала должен сработать главный поток, а потом
Так вот как оно работает. Я думал, что код просто выполняется одновременно в двух местах

2021-02-15 18:29 UTC, merged